### ISSUE TITLE
Align to Dan-actions (v1.1)

### ISSUE THREAD

**Issue by librasteve** [p6steve/raku-Dan-Polars#1]
12:41 < discord-raku-bot> <Anton Antonov#7232> <@928301352029937715> Sounds good. To be more concrete, my proposal is to make another, Dan-actions file here: 
                          https://github.com/antononcube/Raku-DSL-English-DataQueryWorkflows/tree/master/lib/DSL/English/DataQueryWorkflows/Actions/Raku

**Comment by librasteve** [comment]
hi @antononcube - I am making progress with this module and would like to start thinking about how it can serve your Raku-DSL needs. I am struggling to get this https://antononcube.shinyapps.io/DSL-evaluations/#section-main to produce any code ... it would be really helpful to me to see the generated code and compare to the source files! 

I wonder if the shinyapps site is just quite slow and I am not sure what to do - should I do (i) cut and paste from example to main, (ii) choose Grammars / from English / to Python and (iii) hit submit?

**Comment by antononcube** [comment]
@p6steve I am not sure that might be the reason. I get code generate quickly enough. 

A few suggestions:

- For data wrangling generation please use `DSL MODULE DataQuery;` line in the DSL specs -- my current "DSL-classifier" does not work reliably.

- Please examine the sub-tabs "Translation" and "Errors". They might be able to provide hints of what is wrong.

- I can share a Jupiter a notebook with you that directly calls that Cross web service. (Instead of using R-Shiny.)

- Maybe, a good alternative is for me to make a Docker file with required DSL packages. 

- If you install the packages  ["DSL::Shared"](https://github.com/antononcube/Raku-DSL-Shared) and  ["DSL::DataQueryWorkflows"](https://github.com/antononcube/Raku-DSL-English-DataQueryWorkflows) locally, on your computer you can generate code with CLI. Here is an example:

```shell
> ToDataQueryWorkflowCode Raku 'use the data table $dfTemp; group by Var1; show counts; ungroup; rename Var1 as VAR01'
# $obj = $dfTemp ;
# $obj = group-by( $obj, "Var1") ;
# say "counts: ", $obj>>.elems ;
# $obj = $obj.values.reduce( -> $x, $y { [|$x, |$y] } ) ;
# $obj = rename-columns( $obj, %("Var1" => "VAR01") )
```

**Comment by librasteve** [comment]
Aha - thanks! OK now - I was missing the DSL MODULE DataQuery; line
